cert

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,33 +1,33 @@
 version: "3.8"
 
 volumes:
- certs:
-   driver: local
- esdata01:
-   driver: local
- esdata02:
-   driver: local
- esdata03:
-   driver: local
- kibanadata:
-   driver: local
- logstashdata01:
-   driver: local
+  esdata01:
+    driver: local
+  esdata02:
+    driver: local
+  esdata03:
+    driver: local
+  kibanadata:
+    driver: local
+  logstashdata01:
+    driver: local
 
 networks:
- default:
-   name: elastic
-   external: false
+  default:
+    name: elastic
+    external: false
 
 services:
  setup:
     image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
     volumes:
-      - certs:/usr/share/elasticsearch/config/certs
+      - ./certs:/usr/share/elasticsearch/config/certs
       - ./instances.yml:/usr/share/elasticsearch/config/instances.yml:ro
     user: "0"
     command: >
       bash -c '
+        echo "Checking instances.yml content";
+        cat /usr/share/elasticsearch/config/instances.yml;
         if [ x${ELASTIC_PASSWORD} == x ]; then
           echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
           exit 1;
@@ -35,16 +35,15 @@ services:
           echo "Set the KIBANA_PASSWORD environment variable in the .env file";
           exit 1;
         fi;
-        if [ ! -f config/certs/ca.zip ]; then
-          echo "Creating CA";
-          bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
-          unzip config/certs/ca.zip -d config/certs;
+        if [ ! -f config/certs/ca/ca.crt ] || [ ! -f config/certs/ca/ca.key ]; then
+          echo "CA not found, exiting";
+          exit 1;
         fi;
-        if [ ! -f config/certs/certs.zip ]; then
-          echo "Creating certs";
-          bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
-          unzip config/certs/certs.zip -d config/certs;
+        if [ ! -f config/certs/es01/es01.crt ] || [ ! -f config/certs/es01/es01.key ]; then
+          echo "Certs not found, exiting";
+          exit 1;
         fi;
+        echo "Using existing certs";
         echo "Setting file permissions"
         chown -R root:root config/certs;
         find . -type d -exec chmod 750 \{\} \;;
@@ -69,7 +68,7 @@ services:
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
-     - certs:/usr/share/elasticsearch/config/certs
+     - ./certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
@@ -114,7 +113,7 @@ services:
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
-     - certs:/usr/share/elasticsearch/config/certs
+     - ./certs:/usr/share/elasticsearch/config/certs
      - esdata02:/usr/share/elasticsearch/data
    ports:
      - 9202:9200
@@ -159,7 +158,7 @@ services:
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
-     - certs:/usr/share/elasticsearch/config/certs
+     - ./certs:/usr/share/elasticsearch/config/certs
      - esdata03:/usr/share/elasticsearch/data
    ports:
      - 9203:9200
@@ -204,7 +203,7 @@ services:
    labels:
      co.elastic.logs/module: kibana
    volumes:
-     - certs:/usr/share/kibana/config/certs
+     - ./certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
